module.exports = twitterData = [
1,"I loooooooovvvvvveee my Kindle.5. Not that the DX is cool, but the .5 is fantastic in its own right.",
1,"Reading my kindle.5...  Love it... Lee childs is good read.",
1,"Ok, first assesment of the #kindle.5 ...it fucking rocks!!!",
1,"You'll love your Kindle.5. I've had mine for a few months and never looked back. The new big one is huge! No need for remorse!",
1," Fair enough. But i have the Kindle.5 and I think it's perfect",
1," no. it is too big. I'm quite happy with the Kindle.5.",
0,"Fuck this economy. I hate aig and their non loan given asses.",
1,"Jquery is my new best friend.",
1,"Loves twitter",
1,"how can you not love Obama? he makes jokes about himself.",
.5,"Check this video out -- President Obama at the White House Correspondents' Dinner http://bit.ly/IMXUM",
0," I firmly believe that Obama/Pelosi have ZERO desire to be civil.  It's a charade and a slogan, but they want to destroy conservatism",
1,"House Correspondents dinner was last night whoopi, barbara &amp; sherri went, Obama got a standing ovation",
1,"Watchin Espn..Jus seen this new Nike Commerical with a Puppet Lebron..sh*t was hilarious...LMAO!!!",
0,"dear nike, stop with the flywire. that shit is a waste of science. and ugly. love, ",
1,"#lebron best athlete of our generation, if not all time (basketball related) I don't want to get into inter-sport debates about   __1/.5",
0,"I was talking to this guy last night and he was telling me that he is a die hard Spurs fan.  He also told me that he hates LeBron James.",
1,"i love lebron. http://bit.ly/PdHur",
0," Lebron is a Beast, but I'm still cheering 1 the A..til the end.",
1," lebron IS THE BOSS",
1," Lebron is a hometown hero to me, lol I love the Lakers but let's go Cavs, lol",
1,"lebron and zydrunas are such an awesome duo",
1," Lebron is a beast... nobody in the NBA comes even close.",
1,"downloading apps for my iphone! So much fun :-) There literally is an app for just about anything.",
1,"good news, just had a call from the Visa office, saying everything is fine.....what a relief! I am sick of scams out there! Stealing!",
1,"http://twurl.nl/epkr1b - awesome come back from  (via )",
1,"In montreal for a long weekend of R&amp;R. Much needed.",
1,"Booz Allen Hamilton has a bad ass homegrown social collaboration platform. Way cool!  #ttiv",
1,"[#MLUC09] Customer Innovation Award Winner: Booz Allen Hamilton -- http://ping.fm/c.5hPP",
1," I current use the Nikon D90 and love it, but not as much as the Canon 10D/50D. I chose the D90 for the  video feature. My mistake.",
.5,"need suggestions for a good IR filter for my canon 10D ... got some? pls DM",
.5,": I just checked my google for my business- blip shows up as the second entry! Huh. Is that a good or ba... ? http://blip.fm/~6emhv",
1," Google is always a good place to look. Should've mentioned I worked on the Mustang w/ my Dad, .",
0,"Played with an android google phone. The slide out screen scares me I would break that fucker so fast. Still prefer my iPhone.",
0,"US planning to resume the military tribunals at Guantanamo Bay... only this time those on trial will be AIG execs and Chrysler debt holders",
0,"omg so bored &amp; my tattoooos are so itchy!!  help! aha =)",
0,"I'm itchy and miserable!",
0," no. I'm not itchy for now. Maybe later, lol.",
1,"RT  I love the nerdy Stanford human biology videos - makes me miss school. http://bit.ly/13t7NR",
1,": Has been a bit crazy, with steep learning curve, but LyX is really good for long docs. For anything shorter, it would be insane.",
1,"I'm listening to P.Y.T by Danny Gokey &lt;3 &lt;3 &lt;3 Aww, he's so amazing. I &lt;3 him so much :)",
1,"is going to sleep then on a bike ride:]",
0,"cant sleep... my tooth is aching.",
0,"Blah, blah, blah same old same old. No plans today, going back to sleep I guess.",
0,"glad i didnt do Bay to Breakers today, it's 1000 freaking degrees in San Francisco wtf",
.5,"is in San Francisco at Bay to Breakers.",
.5,"just landed at San Francisco",
.5,"San Francisco today.  Any suggestions?",
0,"?Obama Administration Must Stop Bonuses to AIG Ponzi Schemers ... http://bit.ly/.5CUIg",
0,"started to think that Citi is in really deep s&amp;^t. Are they gonna survive the turmoil or are they gonna be the next AIG?",
0,"ShaunWoo hate'n on AiG",
1," you will not regret going to see Star Trek. It was AWESOME!",
.5,"On my way to see Star Trek  Esquire.",
.5,"Going to see star trek soon with my dad.",
0,"annoying new trend on the internets:  people picking apart michael lewis and malcolm gladwell.  nobody wants to read that.",
.5,"Bill Simmons in conversation with Malcolm Gladwell http://bit.ly/j9o50",
1,"Highly recommend: http://tinyurl.com/HowDavidBeatsGoliath by Malcolm Gladwell",
1,"Blink by malcolm gladwell amazing book and The tipping point!",
1,"Malcolm Gladwell might be my new man crush",
0,"omg. The commercials alone on ESPN are going to drive me nuts.",
1," Playing with Twitter API sounds fun.  May need to take a class or find a new friend who like to generate results with API code.",
.5,"playing with cURL and the Twitter API",
1,"Hello Twitter API ;)",
.5,"playing with Java and the Twitter API",
0," Because the twitter api is slow and most client's aren't good.",
0,"yahoo answers can be a butt sometimes",
1,"is scrapbooking with Nic =D",
1,"RT : Five Things Wolfram Alpha Does Better (And Vastly Different) Than Google - http://bit.ly/6nSnR",
1,"just changed my default pic to a Nike basketball cause bball is awesome!!!!!",
.5,"Nike owns NBA Playoffs ads w/ LeBron, Kobe, Carmelo? http://ow.ly/7Uiy  #Adidas #Billups #Howard  #Marketing #Branding",
.5,"Next time, I'll call myself Nike'",
.5,"New blog post: Nike SB Dunk Low Premium 'White Gum' http://tr.im/lOtT",
0,"RT : Was just told that Nike layoffs started today :-(",
1,"Back when I worked for Nike we had one fav word : JUST DO IT! :)",
1,"By the way, I'm totally inspired by this freaky Nike commercial: http://snurl.com/icgj9",
.5,"giving weka an app engine interface, using the bird strike data for the tests, the logo is a given.",
.5,"Brand New Canon EOS 50D 15MP DSLR Camera Canon 17-85mm IS Lens ...: Web Technology Thread, Brand New Canon EOS 5.. http://u.mavrev.com/5a3t",
1,"Class... The 50d is supposed to come today :)",
0,"needs someone to explain lambda calculus to him! :(",
0,"Took the Graduate Field Exam for Computer Science today.  Nothing makes you feel like more of an idiot than lambda calculus.",
1,"SHOUT OUTS TO ALL EAST PALO ALTO FOR BEING IN THE BUILDIN KARIZMAKAZE 50CAL GTA! ALSO THANKS TO PROFITS OF DOOM UNIVERSAL HEMPZ CRACKA......",
0," Yeahhhhhhhhh, I wouldn't really have lived in East Palo Alto if I could have avoided it.  I guess it's only for the summer.",
1,"  Great Stanford course. Thanks for making it available to the public! Really helpful and informative for starting off!",
.5,"NVIDIA Names Stanford's Bill Dally Chief Scientist, VP Of Research http://bit.ly/Fvvg9",
.5,"New blog post: Harvard Versus Stanford - Who Wins? http://bit.ly/MCoCo",
1," til 6pm... lets go lakers!!!",
0,"Damn you North Korea. http://bit.ly/KtMeQ",
0,"Can we just go ahead and blow North Korea off the map already?",
0,"North Korea, please cease this douchebaggery. China doesn't even like you anymore. http://bit.ly/NeHSl",
0,"Why the hell is Pelosi in freakin China? and on whose dime?",
0,"Are YOU burning more cash $$$ than Chrysler and GM? Stop the financial tsunami. Where bailout means taking a handout!",
0,"insects have infected my spinach plant :(",
0,"wish i could catch every mosquito in the world n burn em slowly.they been bitin the shit outta me .5day.mosquitos are the assholes of insects",
0,"just got back from church, and I totally hate insects.",
0,"Just got mcdonalds goddam those eggs make me sick. O yeah Laker up date go lakers. Not much of an update? Well it's true so suck it",
1,"omgg i ohhdee want mcdonalds damn i wonder if its open lol =]",
0,"History exam studying ugh",
0,"I hate revision, it's so boring! I am totally unprepared for my exam tomorrow :( Things are not looking good...",
0,"Higher physics exam tommorow, not lookin forward to it much :(",
0,"It's a bank holiday, yet I'm only out of work now. Exam season sucks:(",
0,"Cheney and Bush are the real culprits - http://fwix.com/article/939196",
0,"Life?s a bitch? and so is Dick Cheney. #p.5 #bipart #tlot #tcot #hhrs #GOP #DNC http://is.gd/DjyQ",
0,"Dick Cheney's dishonest speech about torture, terror, and Obama. -Fred Kaplan Slate. http://is.gd/DiHg",
0,"The Republican party is a bunch of anti-abortion zealots who couldn't draw flies to a dump. -- Neal Boortz (just now, on the radio)",
0,"is Twitter's connections API broken? Some tweets didn't make it to Twitter...",
0,"i srsly hate the stupid twitter API timeout thing, soooo annoying!!!!! :(",
1," I really liked 's Learning jQuery book. http://bit.ly/pg0lT is worth a look too",
.5,"jQuery UI 1.6 Book Review - http://cfbloggers.org/?c=30631",
1,"Very Interesting Ad from Adobe by Goodby, Silverstein &amp; Partners - YouTube - Adobe CS1: Le Sens Propre http://bit.ly/VprpT",
1,"Goodby Silverstein agency new site! http://www.goodbysilverstein.com/ Great!",
1,"RT  Goodby, Silverstein's new site: http://www.goodbysilverstein.com/ I enjoy it. *nice find!*",
1,"The ever amazing Psyop and Goodby Silverstein &amp; Partners for HP! http://bit.ly/g.5rU8 Have to go play with After Effects now!",
1,"top ten most watched on Viral-Video Chart.  Love the nike #mostvaluablepuppets campaign from Wieden &amp; Kennedy http://bit.ly/nR1n9",
1,"zomg!!! I have a G.5!!!!!!!",
1,"Ok so lots of buzz from IO.5009 but how lucky are they - a Free G.5!! http://is.gd/Hyzl",
1,"just got a free G.5 android at google i/o!!!",
1,"Guess I'll be retiring my G1 and start using my developer G.5 woot #googleio",
.5,"At GWT fireside chat ",
1,"I am happy for Philip being at GoogleIO today",
1,"Lakers played great!  Cannot wait for Thursday night Lakers vs. ???",
.5,"Hi there, does anyone have a great source for advice on viral marketing?... http://link.gs/YtZ8",
1,"Judd Apatow creates fake sitcom on NBC.com to market his new movie... viral marketing at its best. http://is.gd/K0yK",
.5,"Here's A case study on how to use viral marketing to add over 10,000 people to your list http://snipr.com/i50oz",
0,"VIRAL MARKETING FAIL. This Acia Pills brand oughta get shut down for hacking into people's messenger's.  i get 5-6 msgs in a day! Arrrgh!",
1,"watching Night at The Museum . Lmao",
1,"i loved night at the museum!!!",
.5,"going to see the new night at the museum  movie with my family oh boy a three year old in the movies fuin",
1,"just got back from the movies.  went to see the new night at the museum with rachel.  it was good",
.5,"Just saw the new Night at the Museum movie...it was...okay...lol 7/10",
.5,"Going to see night at the museum .5 with tall boy",
1," I will take you on a date to see night at the museum .5 whenever you want...it looks soooooo good",
1,"no watching The Night At The Museum. Getting Really Good",
1,"Night at the Museum, Wolverine and junk food - perfect monday!",
1,"saw night at the museum .5 last night.. pretty crazy movie.. but the cast was awesome so it was well worth it. Robin Williams forever!",
.5,"I saw Night at the Museum: Battle of the Swithsonian today. It was okay. Your typical [kids] Ben Stiller movie.",
.5,"Taking Katie to see Night at the Museum.  (she picked it)",
0,"Night at the Museum tonite instead of UP. :( oh well. that 1 yr old better enjoy it. LOL",
.5,"GM says expects announcment on sale of Hummer soon - Reuters: WDSUGM says expects announcment on sale of Hummer .. http://bit.ly/1E1Fv",
0,"It's unfortunate that after the Stimulus plan was put in place twice to help GM on the back of the American people has led to the inevitable",
0,"Tell me again why we are giving more $$ to GM?? We should use that $ for all the programs that support the unemployed.",
0," oh yes but if GM dies it will only be worth more boo hahaha",
0,"Time Warner cable is down again 3rd time since Memorial Day bummer!",
0,"I would rather pay reasonable yearly taxes for free fast internet, than get gouged by Time Warner for a slow connection.",
0,"NOOOOOOO my DVR just died and I was only half way through the EA presser. Hate you Time Warner",
0,"F*ck Time Warner Cable!!! You f*cking suck balls!!! I have a $700 HD tv &amp; my damn HD channels hardly ever come in. Bullshit!!",
0,"time warner has the worse customer service ever. I will never use them again",
0,"Time warner is the devil. Worst possible time for the Internet to go out.",
0,"Fuck no internet damn time warner!",
0,"time warner really picks the worst time to not work. all i want to do is get to mtv.com so i can watch the hills. wtfffff.",
0,"I hate Time Warner! Soooo wish I had Vios. Cant watch the fricken Mets game w/o buffering. I feel like im watching free internet porn.",
0,"Ahh...got rid of stupid time warner today &amp; now taking a nap while the roomies cook for me. Pretty good end for a monday :)",
0,"Time Warner's HD line up is crap.",
0,"is being fucked by time warner cable. didnt know modems could explode. and Susan Boyle sucks too!",
.5,"Time Warner Cable Pulls the Plug on 'The Girlfriend Experience' - (www.tinyurl.com/m595fk)",
0,"Time Warner Cable slogan: Where calling it a day at .5pm Happens.",
.5,"Rocawear Heads to China, Building 300 Stores  - http://tinyurl.com/nofet3",
.5,"Climate focus turns to Beijing: The United Nations, the US and European governments have called on China to co-o.. http://tinyurl.com/lto9.5n",
.5,"myfoxdc Barrie Students Back from Trip to China: A Silver Spring high school's class trip to China has en.. http://tinyurl.com/nlhqba",
.5,"Three China aerospace giants develop Tianjin Binhai  New Area,  .5.5.9 B yuan invested   http://bit.ly/mMiDv",
.5,"http://xi.gs/01FO GM CEO: China will continue to be key partner",
.5,"RT  is now the time to buy a GM car? http://bit.ly/nRzlu",
0,"Recovering from surgery..wishing  was here :(",
1,"My wrist still hurts. I have to get it looked at. I HATE the dr/dentist/scary places. :( Time to watch Eagle eye. If you want to join, txt!",
.5,"Dentist tomorrow. Have to brush well in the morning. Like I make my hair all nice before I get it cut. Why?",
0,"THE DENTIST LIED!  U WON'T FEEL ANY DISCOMORT! PROB WON'T EVEN NEED PAIN PILLS MAN U TWIPPIN THIS SHIT HURT!! HOW MANY PILLS CAN I TAKE!!",
0," my dentist is great but she's expensive...=(",
.5," Pet Dentist http://www.funnyville.com/fv/pictures/dogdentures.shtml",
1,"is studing math ;) tomorrow exam and dentist :)",
0,"my dentist was wrong... WRONG",
0,"Going to the dentist later.:|",
0,"Son has me looking at cars online.  I hate car shopping.  Would rather go to the dentist!  Anyone with a good car at a good price to sell?",
.5,"NCAA Baseball Super Regional - Rams Club http://bit.ly/Ro7nx",
.5,"just started playing Major League Baseball .5K9. http://raptr.com/H3LLGWAR",
.5,"Cardinals baseball advance to Super Regionals. Face CS-Fullerton Friday.",
.5,"Sony coupon code.. Expires soon.. http://www.coupondork.com/r/1796",
.5,"waiting in line at safeway.",
0,"luke and i got stopped walking out of safeway and asked to empty our pockets and lift our shirts. how jacked up is that?",
.5,"Did not realize there is a gym above Safeway!",
.5," I have three words for you: Safeway dot com",
1,"Safeway is very rock n roll tonight",
.5,"Bout to hit safeway I gotta eat",
.5,"Jake's going to safeway!",
.5,"Found a safeway. Picking up a few staples.",
.5,"Safeway Super-marketing via mobile coupons http://bit.ly/ONH7w",
0,"The safeway bathroom still smells like ass!",
0,"At safeway on elkhorn, they move like they're dead!",
.5,"Your Normal Weight (and How to Get There) ? Normal Eating Blog http://bit.ly/ZeT8O",
.5,"Is Eating and Watching Movies....",
.5,"eating sashimi",
.5,"is eating  home made yema",
.5,"eating cake",
1,"i love Dwight Howard's vitamin water commercial... now i wish he was with NIKE and not adidas. lol.",
0,"Found NOTHING at Nike Factory :/ Off to Banana Republic Outlet! http://myloc.me/.5zic",
.5,"iPhone May Get Radio Tagging and Nike  : Recently-released iTunes version 8..5 suggests that VoiceOver functional.. http://tinyurl.com/oq5ctc",
1,"is lovin his Nike  already and that's only from running on the spot in his bedroom",
.5,"Launched! http://imgsearch.net  #imgsearch #ajax #jquery #webapp",
1," I finally got around to using jquery to make my bio collapse. Yay for slide animations.",
.5,"RT : The Ultimate jQuery List - http://jquerylist.com/",
.5,"I just extracted and open-sourced a jQuery plugin from Stormweight to highlight text with a regular expression: http://bit.ly/ybJKb",
.5," what was the php jquery hack?",
.5,"jQuery Cheat Sheet http://www.javascripttoolbox.com/jquery/cheatsheet/",
.5,"Beginning JavaScript and CSS Development with jQuery #javascript #css #jquery http://bit.ly/TO3e5",
1," right!!! LOL we'll get there!! I have high expectations, Warren Buffet style.",
1,"RT : RT GREAT  Someone's sitting in the shade today because someone planted a tree a long time ago.- Warren Buffet",
.5,"Warren Buffet on the economy http://ping.fm/Lau0p",
1,"Warren Buffet became (for a time) the richest man in the United States, not by working but investing in 1 Big idea which lead to the fortune",
1,"According to the create a school, Notre Dame will have 7 receivers in NCAA 10 at 81 or higher rating :) *sweet*",
.5,"All-Star Basketball Classic Tuesday Features Top Talent: Chattanooga's Notre Dame High School will play host.. http://bit.ly/qltJA",
1," it's definitely under warranty &amp; my experience is the amazon support for kindle is great! had to contact them about my kindle.5",
.5,"RT Look, Available !Amazon Kindle.5 &amp; Kindle DX, Get it Here: http://short.to/87ub The Top Electronic Book Reader Period, free .5 day ship ...",
0,"Time Warner Road Runner customer support here absolutely blows. I hate not having other high-speed net options. I'm ready to go nuclear.",
0,"Time Warner cable phone reps r dumber than nails!!!!! UGH! Cable was working 10 mins ago now its not WTF!",
0," we tried but Time Warner wasn't being nice so we recorded today. :)",
0,"OMG - time warner f'ed up my internet install - instead of today  its now NEXT saturday - another week w/o internet! &amp;$*ehfa^V9fhg[*# fml.",
0,"wth..i have never seen a line this loooong at time warner before, ugh.",
0,"Impatiently awaiting the arrival of the time warner guy. It's way too pretty to be inside all afternoon",
.5,"Man accosts Roger Federer during French Open http://ff.im/3HCPT",
0,"Naive Bayes using EM for Text Classification. Really Frustrating...",
1,"We went to Stanford University today. Got a tour. Made me want to go back to college. It's also decided all of our kids will go there.",
.5,"Investigation pending on death of Stanford CS prof / Google mentor Rajeev Motwani http://bit.ly/LwOUR tip ",
.5,"I'm going to bed. It was a successful weekend. Stanford, here I come.",
0," If you're being harassed by calls about your car warranty, changing your number won't fix that. They call every number. #d-bags",
0,"Just blocked United Blood Services using Google Voice. They call more than those Car Warranty guys.",
0,"#at&amp;t is complete fail.",
0," OH SNAP YOU WORK AT AT&amp;T DON'T YOU",
0," i really dont want AT&amp;T phone service..they suck when it comes to having a signal",
0,"I say we just cut out the small talk: AT&amp;T's new slogan: F__k you, give us your money. (Apologies to Bob Geldof.)",
0,"pissed about at&amp;t's mid-contract upgrade price for the iPhone (it's $.500 more) I'm not going to pay $199 for something I thought was $.599",
0,"Safari 1 is fast :) Even on my shitty AT&amp;T tethering.",
0," What is AT&amp;T fucking up?",
0,"    AT&amp;T dropped the ball and isn't supporting crap with the new iPhone 3.0... FAIL #att SUCKS!!!",
0," yay, glad you got the phone! Still, damn you, AT&amp;T.",
.5,"Google Wave Developer Sandbox Account Request http://bit.ly/.5NYlc",
0,"Talk is Cheap: Bing that, I?ll stick with Google. http://bit.ly/XC3C8",
0," WTF is the point of deleting tweets if they can still be found in summize and searches? Twitter, please fix that. Thanks and bye",
.5," have google profiles stopped showing up in searches? cant see them anymore",
1," I love Google Translator too ! :D Good day mate !",
1,"reading on my new Kindle.5!",
1,"My Kindle.5 came and I LOVE it! :)",
1,"LOVING my new Kindle.5.  Named her Kendra in case u were wondering. The cookbook is THE tool cuz it tells u all the tricks!  Best gift EVR!",
0,"The real AIG scandal / http://bit.ly/b8.5Px",
.5,"Any twitter to aprs apps yet?",
.5,"15 Pros You Should Be Following on Twitter - http://is.gd/sMbZ",
1,"Obama is quite a good comedian! check out his dinner speech on CNN :) very funny jokes.",
1," Barack Obama shows his funny side  &gt;&gt; http://tr.im/l0gY !! Great speech..",
1,"I like this guy : ' Barack Obama shows his funny side  &gt;&gt; http://tr.im/l0gY !!",
1,"Obama's speech was pretty awesome last night! http://bit.ly/IMXUM",
1,"Reading  Bill Clinton Fail - Obama Win? http://tinyurl.com/pcyxj7",
1,"Obama More Popular Than U.S. Among Arabs: Survey: President Barack Obama's popularity in leading Arab countries .. http://tinyurl.com/prlvqu",
1,"Obama's got JOKES!! haha just got to watch a bit of his after dinner speech from last night... i'm in love with mr. president ;)",
0,"LEbron james got in a car accident i guess..just heard it on evening news...wow i cant believe it..will he be ok ? http://twtad.com/69750",
1,"is it me or is this the best the playoffs have been in years oh yea lebron and melo in the finals",
1," No, Lebron is the best",
1," LeBron is cool.  I like his personality...he has good character.",
1,"Watching Lebron highlights. Damn that niggas good",
1," Lebron is MURDERING shit.",
1," LeBron is a monsta and he is only .51. SMH The world ain't ready.",
1," when Lebron is done in the NBA he will probably be greater than Kobe. Like u said Kobe is good but there alot of 'good' players.",
1,"KOBE IS GOOD BT LEBRON HAS MY VOTE",
0,"Kobe is the best in the world not lebron .",
1," World Cup .5010 Access?? Damn, that's a good look!",
1,"Just bought my tickets for the .5010 FIFA World Cup in South Africa. Its going to be a great summer. http://bit.ly/9GEZI",
.5,"Share: Disruption...Fred Wilson's slides for his talk at Google HQ  http://bit.ly/Bo8PG",
0,"I have to go to Booz Allen Hamilton for a .5hr meeting :(  But then i get to go home :)",
1,"The great Indian tamasha truly will unfold from May 16, the result day for Indian General Election.",
1," I have the Kindle.5. I've seen pictures of the DX, but haven't seen it in person. I love my Kindle - I'm on it everyday.",
1," Such an awesome idea - the  continual learning program with a Kindle.5  http://bit.ly/1ZLfF",
.5,"ok.. do nothing.. just thinking about 10D",
1," Ooooh, what model are you getting??? I have the 10D and LOVE LOVE LOVE LOVE it!",
1,"The Times of India: The wonder that is India's election. http://bit.ly/p7u1H",
1,"http://is.gd/ArUJ Good video from Google on using search options.",
0," lol. Ah my skin is itchy :( damn lawnmowing.",
0,"itchy back!! dont ya hate it!",
1,"Stanford Charity Fashion Show a top draw http://cli.gs/NeNuAH",
1,"Stanford University?s Facebook Profile is One of the Most Popular Official University Pages - http://tinyurl.com/p5b3fl",
1,"Lyx is cool.",
1,"SOOO DISSAPOiNTED THEY SENT DANNY GOKEY HOME... YOU STiLL ROCK ...DANNY ... MY HOMETOWN HERO !! YEAH MiLROCKEE!!",
1,"RT  'American Idol' fashion: Adam Lambert tones down, Danny Gokey cute ... http://cli.gs/7JWSHV",
1," I love you DANNY GOKEY!! :)",
.5,"RT : RT  GM OnStar now instantly sends accident location coordinates to 911 | GPS Obsessed http://bit.ly/16szL1",
0,"so tired. i didn't sleep well at all last night.",
0,"Boarding plane for San Francisco in 1 hour; 6 hr flight. Blech.",
0,"bonjour San Francisco. My back hurts from last night..",
.5,"breakers. in San Francisco, CA http://loopt.us/1v88Bw.t",
.5,"Heading to San Francisco",
1,"With my best girl for a few more hours in San francisco. Mmmmmfamily is wonderful!",
0,"F*** up big, or go home - AIG",
1,"Went to see the Star Trek movie last night.  Very satisfying.",
1,"I can't wait, going to see star trek tonight!!",
1,"Star Trek was as good as everyone said!!",
1,"am loving new malcolm gladwell book - outliers",
1,"I highly recommend Malcolm Gladwell's 'The Tipping Point.' My next audiobook will probably be one of his as well.",
0,"Malcolm Gladwell is a genius at tricking people into not realizing he's a fucking idiot",
0," hey no offense but malcolm gladwell is a pretenious, annoying cunt and he brings you down. cant read his shit",
1,"RT : http://bit.ly/SOYv7  Great article by Malcolm Gladwell.",
1,"I seriously underestimated Malcolm Gladwell.  I want to meet this dude.",
0,"i hate comcast right now. everything is down cable internet &amp; phone....ughh what am i to do",
0,"Comcast sucks.",
0,"The day I never have to deal with Comcast again will rank as one of the best days of my life.",
0," did comcast fail again??",
.5,"How do you use the twitter API?... http://bit.ly/1VBhH",
0,"curses the Twitter API limit",
0,"Now I can see why Dave Winer screams about lack of Twitter API, its limitations and access throttles!",
.5,"testing Twitter API",
0,"Arg. Twitter API is making me crazy.",
.5,"Testing Twitter API. Remote Update",
1,"I'm really loving the new search site Wolfram/Alpha. Makes Google seem so ... quaint. http://www7.5.wolframalpha.com/",
0,"#wolfram Alpha SUCKS! Even for researchers the information provided is less than you can get from #google or #wikipedia, totally useless!",
1,"Off to the NIKE factory!!!",
1,"New nike muppet commercials are pretty cute. Why do we live together again?",
.5,"New blog post: Nike Zoom LeBron Soldier 3 (III) - White / Black - Teal http://bit.ly/rouUS",
.5,"New blog post: Nike Trainer 1 http://bit.ly/391bp",
0," oh those are awesome! i so wish they weren't owned by nike :(",
1," http://twitpic.com/5c7uj - AWESOME!!! Seeing the show Friday at the Shoreline Amphitheatre. Never seen NIN before. Can't wait. ...",
0,"arhh, It's weka bug. = = and I spent almost two hours to find that out. crappy me",
1," hey bud :) np I do so love my 50D, although I'd love a 5D mkII more",
1,"  just got us a 50D for the office. :D",
1,"Just picked up my new Canon 50D...it's beautiful!!  Prepare for some seriously awesome photography!",
1,"Just got my new toy. Canon 50D. Love love love it!",
1,"Learning about lambda calculus :)",
.5,"#jobs #sittercity Help with taking care of sick child (East Palo Alto, CA) http://tinyurl.com/qwrr.5m",
1,"I'm moving to East Palo Alto!",
1," I just finished watching your Stanford iPhone Class session. I really appreciate it. You Rock!",
1," Hi! Just saw your Stanford talk and really liked your advice. Just saying Hi from Singapore (yes the videos do get around)",
.5,"#MBA Admissions Tips Stanford GSB Deadlines and Essay Topics .5009-.5010 http://tinyurl.com/pet1fd",
.5,"Ethics and nonprofits - http://bit.ly/qsXRp  #stanford #socialentrepreneurship",
1,"LAKERS tonight let's go!!!!",
1,"Will the Lakers kick the Nuggets ass tonight?",
0,"Oooooooh... North Korea is in troubleeeee! http://bit.ly/19epAH",
0,"Wat the heck is North Korea doing!!??!! They just conducted powerful nuclear tests! Follow the link: http://www.msnbc.msn.com/id/309.51379",
0,"Listening to Obama... Friggin North Korea...",
0,"I just realized we three monkeys in the white Obama.Biden,Pelosi . Sarah Palin .501.5",
0," Pelosi should stay in China and never come back.",
0,"Nancy Pelosi gave the worst commencement speech I've ever heard. Yes I'm still bitter about this",
0,"ugh. the amount of times these stupid insects have bitten me. Grr..",
1,"Prettiest insects EVER - Pink Katydids: http://bit.ly/.5Upw.5p",
0,"Just got barraged by a horde of insects hungry for my kitchen light. So scary.",
1,"Just had McDonalds for dinner. :D It was goooood. Big Mac Meal. ;)",
1,"AHH YES LOL IMA TELL MY HUBBY TO GO GET ME SUM MCDONALDS =]",
1,"Stopped to have lunch at McDonalds. Chicken Nuggetssss! :) yummmmmy.",
1,"Could go for a lot of McDonalds. i mean A LOT.",
1,"my exam went good. : your prayers worked (:",
1,"Only one exam left, and i am so happy for it :D",
0,"Math review. Im going to fail the exam.",
0,"Colin Powell rocked yesterday on CBS. Cheney needs to shut the hell up and go home.Powell is a man of Honor and served our country proudly",
0,"obviously not siding with Cheney here: http://bit.ly/19j.5d",
1,"Absolutely hilarious!!! from :  http://bit.ly/bccWt",
1," I never did thank you for including me in your Top 100 Twitter Authors! You Rock! (&amp; I New Wave :-D) http://bit.ly/EOrFV",
.5,"Learning jQuery 1.3 Book Review - http://cfbloggers.org/?c=306.59",
1,"RT : Awesome JQuery reference book for Coda! http://www.macpeeps.com/coda/ #webdesign",
1,"I've been sending e-mails like crazy today to my contacts...does anyone have a contact at Goodby SIlverstein...I'd love to speak to them",
.5,"Adobe CS1 commercial by Goodby Silverstein: http://bit.ly/1aikhF",
1,"Goodby, Silverstein's new site... http://www.goodbysilverstein.com/ I enjoy it.",
1,"Wow everyone at the Google I/O conference got free G.5's with a month of unlimited service",
1," dood I got a free google android phone at the I/O conference. The G.5!",
1," the G.5 is amazing btw, a HUGE improvement over the G1",
1,"HTML 5 Demos! Lots of great stuff to come! Yes, I'm excited. :) http://htmlfive.appspot.com #io.5009 #googleio",
1," http://twitpic.com/6.5shi - Yay! Happy place! Place place!  I love Google!",
1,"#GoogleIO | O3D - Bringing 3d graphics to the browser. Very nice tbh. Funfun.",
1,"Awesome viral marketing for Funny People http://www.nbc.com/yo-teach/",
.5,"Watching a programme about the life of Hitler, its only enhancing my geekiness of history.",
0,"saw night at the museum out of sheer desperation. who is funding these movies?",
1,"Night At The Museum .5? Pretty furkin good.",
1,"Watching Night at the Museum - giggling.",
.5," Jenna, I went to see Night At The Museum .5 today and I was so surprised to see three cast members from The Office...",
.5,"About to watch Night at the Museum with Ryan and Stacy",
.5,"Getting ready to go watch Night at the Museum .5.  Dum dum, you give me gum gum!",
0,"Back from seeing 'Star Trek' and 'Night at the Museum.' 'Star Trek' was amazing, but 'Night at the Museum' was; eh.",
1,"just watched night at the museum .5! so stinkin cute!",
1,"So, Night at the Museum .5 was AWESOME! Much better than part 1. Next weekend we'll see Up.",
.5,"I think I may have a new favorite restaurant. On our way to see Night at the Museum .5.",
.5,"UP! was sold out, so i'm seeing Night At The Museum .5. I'm __ years old.",
1,"saw the new Night at the Museum and i loved it. Next is to go see UP in 3D",
0,"It is a shame about GM. What if they are forced to make only cars the White House THINKS will sell? What do you think?",
0,"As u may have noticed, not too happy about the GM situation, nor AIG, Lehman, et al",
.5,"Obama: Nationalization of GM to be short-term   (AP) http://tinyurl.com/md317r",
0," $GM good riddance.  sad though.",
0,"I Will NEVER Buy a Government Motors Vehicle: Until just recently, I drove GM cars. Since 1988, when I bought a .. http://tinyurl.com/lulsw8",
0,"Having the old Coca-Cola guy on the GM board is stupid has heck! #tcot #ala",
0,"#RantsAndRaves The worst thing about GM (concord / pleasant hill / martinez): is the fucking UAW. ..   http://buzzup.com/1ueb",
0,"Give a man a fish, u feed him for the day. Teach him to fish, u feed him for life. Buy him GM, and u F**K him over for good.",
0,"The more I hear about this GM thing the more angry I get. Billions wasted, more bullshit. All for something like 10k employees and all the..",
0," i own a GM car and it is junk as far as quality compared to a honda",
0,"sad day...bankrupt GM",
0,"is upset about the whole GM thing. life as i know it is so screwed up",
0,"whoever is running time warner needs to be repeatedly raped by a rhino so they understand the consequences of putting out shitty cable svcs",
.5,"Time Warner CEO hints at online fees for magazines      (AP) - Read from Mountain View,United States. Views 16.509 http://bit.ly/UdFCH",
0,"#WFTB Joining a bit late. My connection was down (boo time warner)",
0,"Cox or Time Warner?  Cox is cheaper and gets a B on dslreports.  TW is more expensive and gets a C.",
0,"i am furious with time warner and their phone promotions!",
0,"Just got home from chick-fil-a with the boys. Damn my internets down =( stupid time warner",
0,"could time-warner cable suck more?  NO.",
0,"Pissed at Time Warner for causin me to have slow internet problems",
0," Ummm, having some Time Warner problems?",
0,"You guys see this?  Why does Time Warner have to suck so much ass?  Really wish I could get U-Verse at my apartment. http://bit.ly/s591j",
0,"RT  The upside to Time Warner: unhelpful phone operators   superslow on-site service. Crap, that's not an upside.",
0,"RT : New Time Warner slogan: Time Warner, where we make you long for the days before cable.",
0,"confirmed: it's Time Warner's fault, not Facebook's, that fb is taking about 3 minutes to load. so tempted to switch to verizon =/",
0," Time Warner = epic fail",
.5,"Lawson to head Newedge Hong Kong http://bit.ly/xLQSD #business #china",
.5,"Weird Piano Guitar House in China! http://u.5s.me/7.5i8",
.5,"Send us your GM/Chevy photos http://tinyurl.com/luzkpq",
0,"I know. How sad is that?  RT : 1st day of hurricane season. That's less scarey than govt taking over GM.",
0,"GM files Bankruptcy, not a good sign...",
1,"yankees won mets lost. its a good day.",
1,"My dentist appt today was actually quite enjoyable.",
0,"I hate the effing dentist.",
.5," i had a dentist appt this morning and had the same conversation!",
0," I hate going to the dentist.. !!!",
0,"i hate the dentist....who invented them anyways?",
0,"this dentist's office is cold :/",
.5,"Check this video out -- David After Dentist http://bit.ly/17aW.5",
.5,"First dentist appointment [in years] on Wednesday possibly.",
.5,"Tom Shanahan's latest column on SDSU and its NCAA Baseball Regional appearance: http://ow.ly/axhu",
.5,"BaseballAmerica.com: Blog: Baseball America Prospects Blog ? Blog ... http://bit.ly/EtT8a",
.5,"Portland city politics may undo baseball park http://tinyurl.com/lpjquj",
.5,"RT : CA Merced's water bottled by Safeway, resold at a profit: Wells are drying up across the county http://tinyurl.com/mb573s",
.5,"dropped her broccoli walking home from safeway! ;( so depressed",
.5," we don't have Safeway.",
1,"Just applied at Safeway!(: Yeeeee!",
0,". Place is a nightmare right now. Bumming.",
.5,"at safeway with dad",
0,"HATE safeway select green tea icecream! bought two cartons, what a waste of money.  &gt;_&lt;",
.5,"Safeway with Marvin, Janelle, and Auntie Lhu",
.5,"Safeway offering mobile coupons http://bit.ly/ONH7w",
.5,"Phillies Driving in the Cadillac with the Top Down in Cali, Win 5-3 - http://tinyurl.com/nzcjqa",
.5,"Saved money by opting for grocery store trip and stocking food in hotel room fridge vs. eating out every night while out of town.",
.5,"Lounging around, eating Taco Bell and watching NCIS before work tonight. Need help staying awake.",
.5,"eating breakfast and then school",
.5,"still hungry after eating....",
.5,"10 tips for healthy eating ? ResultsBy Fitness Blog :: Fitness ... http://bit.ly/6.5gFn",
.5,"with the boyfriend, eating a quesadilla",
.5,"Eating dinner. Meat, chips, and risotto.",
.5,"got a new pair of nike shoes. pics up later",
.5,"Nike SB Blazer High ACG Custom - Brad Douglas - http://timesurl.at/15a118",
1,"Nike rocks. I'm super grateful for what I've done with them :) &amp; the European Division of NIKE is BEYOND!  ",
.5,"Nike Air Yeezy Khaki/Pink Colorway Release - http://shar.es/bjfN",
1," have you tried Nike  ? V. addictive.",
.5," That looks an awful lot like one of Nike's private jets....I'm just sayin....",
1,"The Nike Training Club (beta) iPhone app looks very interesting.",
0,"argghhhh why won't  my jquery appear in safari bad safari !!!",
.5,"DevSnippets : jQuery Tools - Javascript UI Components for the Web... http://inblogs.org/go/hfuqt",
.5,"all about Ajax,jquery ,css ,JavaScript and more... (many examples) http://ajaxian.com/",
1,"I'm ready to drop the pretenses, I am forever in love with jQuery, and I want to marry it. Sorry ladies, this nerd is jquery.spokenFor.js",
.5,"This is cold.. I was looking at google's chart//visualization API and found this jQuery wrapper for the API...  http://tinyurl.com/mq5.5bq",
.5,"I spent most of my day reading a jQuery book. Now to start drinking some delirium tremens.",
.5,"jquery Selectors http://codylindley.com/jqueryselectors/",
.5,"How to implement a news ticker with jQuery and ten lines of code http://bit.ly/CZnFJ",
.5,"What's Buffet Doing? Warren Buffett Kicks Butt In Battle of the Boots: Posted By:Alex Crippe.. http://bit.ly/AUIzO",
1,"SUPER INVESTORS: A great weekend read here from Warren Buffet. Oldie, but a goodie. http://tinyurl.com/oqxgga",
.5,"I'm truly braindead.  I couldn't come up with Warren Buffet's name to save my soul",
1,"reading Michael Palin book, The Python Years...great book. I also recommend Warren Buffet &amp; Nelson Mandela's bio",
1,"I mean, I'm down with Notre Dame if I have to.  It's a good school, I'd be closer to Dan, I'd enjoy it.",
0,"I can't watch TV without a Tivo.  And after all these years, the Time/Warner DVR  STILL sucks. http://www.davehitt.com/march03/twdvr.html",
1,"I'd say some sports writers are idiots for saying Roger Federer is one of the best ever in Tennis.  Roger Federer is THE best ever in Tennis",
0,"I still love my Kindle.5 but reading The New York Times on it does not feel natural. I miss the Bloomingdale ads.",
1,"I love my Kindle.5. No more stacks of books to trip over on the way to the loo.",
0,"Although today's keynote rocked, for every great announcement, AT&amp;T shit on us just a little bit more.",
0," - its not so much my obsession with cell phones, but the iphone!  i'm a slave to at&amp;t forever because of it. :)",
.5," oh I see. I thought AT&amp;T were 900MHz WCDMA?",
.5," Where did you read about tethering support Phil?  Just AT&amp;T or will O.5 be joining in?",
0,"Fuzzball is more fun than AT&amp;T ;P http://fuzz-ball.com/twitter",
0,"Today is a good day to dislike AT&amp;T. Vote out of office indeed, ",
1,"GOT MY WAVE SANDBOX INVITE! Extra excited! Too bad I have class now... but I'll play with it soon enough! #io.5009 #wave",
0,"looks like summize has gone down. too many tweets from WWDC perhaps?",
.5,"I hope the girl at work  buys my Kindle.5",
.5,"Missed this insight-filled May column: One smart guy looking closely at why he's impressed with Kindle.5 http://bit.ly/i0peY ",
1," Thanks so much!!! ...from one of your *very* happy Kindle.5 winners ; ) I was so surprised, fabulous. Thank you! Best, Kathleen",
0,"Man I kinda dislike Apple right now. Case in point: the iPhone 3GS. Wish there was a video recorder app. Please?? http://bit.ly/DZm1T",
1," I have a Kindle.5 (&amp; Sony PRS-500). Like it! Physical device feels good. Font is nice. Pg turns are snappy enuf. UI a little klunky.",
1,"The #Kindle.5 seems the best eReader, but will it work in the UK and where can I get one?",
1,"I have a google addiction. Thank you for pointing that out, . Hahaha.",
.5," My primary debit card is Visa Electron.",
.5,"Off to the bank to get my new visa platinum card",
0,"dearest , you rich bastards! the VISA card you sent me doesn't work. why screw a little guy like me?",
.5,"has a date with bobby flay and gut fieri from food network",
1,"Excited about seeing Bobby Flay and Guy Fieri tomorrow at the Great American Food &amp; Music Fest!",
1,"Gonna go see Bobby Flay .5moro at Shoreline. Eat and drink. Gonna be good.",
1,"can't wait for the great american food and music festival at shoreline tomorrow.  mmm...katz pastrami and bobby flay. yes please.",
1,"My dad was in NY for a day, we ate at MESA grill last night and met Bobby Flay. So much fun, except I completely lost my voice today.",
0,"Fighting with LaTex. Again...",
0," we love you too and don't want you to die!!!!!!  Latex = the devil",
0,"7 hours. 7 hours of inkscape crashing, normally solid as a rock. 7 hours of LaTeX complaining at the slightest thing. I can't take any more.",
.5,"How to Track Iran with Social Media: http://bit.ly/.5BoqU",
0,"Shit's hitting the fan in Iran...craziness indeed #iranelection",
0,"Monday already. Iran may implode. Kitchen is a disaster.  seems happy.  had a nice weekend and  is great. whoop.",
.5,"Twitter Stock buzz: $AAPL $ES_F $SPY $SPX $PALM  (updated: 1.5:00 PM)",
1,"getting ready to test out some burger receipes this weekend. Bobby Flay has some great receipes to try. Thanks Bobby.",
.5," is Bobby Flay joining you?",
1,"i lam so in love with Bobby Flay... he is my favorite. RT :  you need a place in Phoenix. We have great peppers here!",
0,"I just created my first LaTeX file from scratch. That didn't work out very well. (See, it's a great time waster)",
1,"using Linux and loving it - so much nicer than windows... Looking forward to using the wysiwyg latex editor!",
1,"After using LaTeX a lot, any other typeset mathematics just looks hideous.",
.5,"Ask Programming: LaTeX or InDesign?: submitted by calcio1 [link] [1 comment] http://tinyurl.com/myfmf7",
0,"On that note, I hate Word. I hate Pages. I hate LaTeX. There, I said it. I hate LaTeX. All you TEXN3RDS can come kill me now.",
1,"Ahhh... back in a *real* text editing environment. I &lt;3 LaTeX.",
0,"Trouble in Iran, I see. Hmm. Iran. Iran so far away. #flockofseagullsweregeopoliticallycorrect",
0,"Reading the tweets coming out of Iran... The whole thing is terrifying and incredibly sad..."
]